#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SvetanFlickrApp
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="FDB")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertFav(Fav instance);
    partial void UpdateFav(Fav instance);
    partial void DeleteFav(Fav instance);
    partial void InsertFavsToDelete(FavsToDelete instance);
    partial void UpdateFavsToDelete(FavsToDelete instance);
    partial void DeleteFavsToDelete(FavsToDelete instance);
    partial void InsertMyPeople(MyPeople instance);
    partial void UpdateMyPeople(MyPeople instance);
    partial void DeleteMyPeople(MyPeople instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::SvetanFlickrApp.Properties.Settings.Default.FDBConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Fav> Favs
		{
			get
			{
				return this.GetTable<Fav>();
			}
		}
		
		public System.Data.Linq.Table<FavsToDelete> FavsToDeletes
		{
			get
			{
				return this.GetTable<FavsToDelete>();
			}
		}
		
		public System.Data.Linq.Table<MyPeople> MyPeoples
		{
			get
			{
				return this.GetTable<MyPeople>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Favs")]
	public partial class Fav : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _photoid;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnphotoidChanging(string value);
    partial void OnphotoidChanged();
    #endregion
		
		public Fav()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_photoid", DbType="NChar(11) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string photoid
		{
			get
			{
				return this._photoid;
			}
			set
			{
				if ((this._photoid != value))
				{
					this.OnphotoidChanging(value);
					this.SendPropertyChanging();
					this._photoid = value;
					this.SendPropertyChanged("photoid");
					this.OnphotoidChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.FavsToDelete")]
	public partial class FavsToDelete : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _photoID;
		
		private System.DateTime _DateAdded;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnphotoIDChanging(string value);
    partial void OnphotoIDChanged();
    partial void OnDateAddedChanging(System.DateTime value);
    partial void OnDateAddedChanged();
    #endregion
		
		public FavsToDelete()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_photoID", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string photoID
		{
			get
			{
				return this._photoID;
			}
			set
			{
				if ((this._photoID != value))
				{
					this.OnphotoIDChanging(value);
					this.SendPropertyChanging();
					this._photoID = value;
					this.SendPropertyChanged("photoID");
					this.OnphotoIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateAdded", DbType="DateTime NOT NULL")]
		public System.DateTime DateAdded
		{
			get
			{
				return this._DateAdded;
			}
			set
			{
				if ((this._DateAdded != value))
				{
					this.OnDateAddedChanging(value);
					this.SendPropertyChanging();
					this._DateAdded = value;
					this.SendPropertyChanged("DateAdded");
					this.OnDateAddedChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MyPeople")]
	public partial class MyPeople : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _UserId;
		
		private string _UserName;
		
		private string _RealName;
		
		private string _Location;
		
		private System.Nullable<bool> _IsFriend;
		
		private System.Nullable<bool> _IsFamily;
		
		private System.Nullable<bool> _IsContact;
		
		private System.Nullable<bool> _IsPro;
		
		private System.Nullable<System.DateTime> _LastPostedImage;
		
		private System.Nullable<System.DateTime> _LastFavedMe;
		
		private System.Nullable<System.DateTime> _LastCommentedMe;
		
		private string _BuddyIconUrl;
		
		private string _IconFarm;
		
		private string _IconServer;
		
		private string _PhotosUrl;
		
		private string _ProfileUrl;
		
		private System.Nullable<System.DateTime> _LastReacted;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUserIdChanging(string value);
    partial void OnUserIdChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnRealNameChanging(string value);
    partial void OnRealNameChanged();
    partial void OnLocationChanging(string value);
    partial void OnLocationChanged();
    partial void OnIsFriendChanging(System.Nullable<bool> value);
    partial void OnIsFriendChanged();
    partial void OnIsFamilyChanging(System.Nullable<bool> value);
    partial void OnIsFamilyChanged();
    partial void OnIsContactChanging(System.Nullable<bool> value);
    partial void OnIsContactChanged();
    partial void OnIsProChanging(System.Nullable<bool> value);
    partial void OnIsProChanged();
    partial void OnLastPostedImageChanging(System.Nullable<System.DateTime> value);
    partial void OnLastPostedImageChanged();
    partial void OnLastFavedMeChanging(System.Nullable<System.DateTime> value);
    partial void OnLastFavedMeChanged();
    partial void OnLastCommentedMeChanging(System.Nullable<System.DateTime> value);
    partial void OnLastCommentedMeChanged();
    partial void OnBuddyIconUrlChanging(string value);
    partial void OnBuddyIconUrlChanged();
    partial void OnIconFarmChanging(string value);
    partial void OnIconFarmChanged();
    partial void OnIconServerChanging(string value);
    partial void OnIconServerChanged();
    partial void OnPhotosUrlChanging(string value);
    partial void OnPhotosUrlChanged();
    partial void OnProfileUrlChanging(string value);
    partial void OnProfileUrlChanged();
    partial void OnLastReactedChanging(System.Nullable<System.DateTime> value);
    partial void OnLastReactedChanged();
    #endregion
		
		public MyPeople()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserId", DbType="NVarChar(200) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				if ((this._UserId != value))
				{
					this.OnUserIdChanging(value);
					this.SendPropertyChanging();
					this._UserId = value;
					this.SendPropertyChanged("UserId");
					this.OnUserIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(200)")]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this.OnUserNameChanging(value);
					this.SendPropertyChanging();
					this._UserName = value;
					this.SendPropertyChanged("UserName");
					this.OnUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RealName", DbType="NVarChar(200)")]
		public string RealName
		{
			get
			{
				return this._RealName;
			}
			set
			{
				if ((this._RealName != value))
				{
					this.OnRealNameChanging(value);
					this.SendPropertyChanging();
					this._RealName = value;
					this.SendPropertyChanged("RealName");
					this.OnRealNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Location", DbType="NVarChar(200)")]
		public string Location
		{
			get
			{
				return this._Location;
			}
			set
			{
				if ((this._Location != value))
				{
					this.OnLocationChanging(value);
					this.SendPropertyChanging();
					this._Location = value;
					this.SendPropertyChanged("Location");
					this.OnLocationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsFriend", DbType="Bit")]
		public System.Nullable<bool> IsFriend
		{
			get
			{
				return this._IsFriend;
			}
			set
			{
				if ((this._IsFriend != value))
				{
					this.OnIsFriendChanging(value);
					this.SendPropertyChanging();
					this._IsFriend = value;
					this.SendPropertyChanged("IsFriend");
					this.OnIsFriendChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsFamily", DbType="Bit")]
		public System.Nullable<bool> IsFamily
		{
			get
			{
				return this._IsFamily;
			}
			set
			{
				if ((this._IsFamily != value))
				{
					this.OnIsFamilyChanging(value);
					this.SendPropertyChanging();
					this._IsFamily = value;
					this.SendPropertyChanged("IsFamily");
					this.OnIsFamilyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsContact", DbType="Bit")]
		public System.Nullable<bool> IsContact
		{
			get
			{
				return this._IsContact;
			}
			set
			{
				if ((this._IsContact != value))
				{
					this.OnIsContactChanging(value);
					this.SendPropertyChanging();
					this._IsContact = value;
					this.SendPropertyChanged("IsContact");
					this.OnIsContactChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsPro", DbType="Bit")]
		public System.Nullable<bool> IsPro
		{
			get
			{
				return this._IsPro;
			}
			set
			{
				if ((this._IsPro != value))
				{
					this.OnIsProChanging(value);
					this.SendPropertyChanging();
					this._IsPro = value;
					this.SendPropertyChanged("IsPro");
					this.OnIsProChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastPostedImage", DbType="DateTime2")]
		public System.Nullable<System.DateTime> LastPostedImage
		{
			get
			{
				return this._LastPostedImage;
			}
			set
			{
				if ((this._LastPostedImage != value))
				{
					this.OnLastPostedImageChanging(value);
					this.SendPropertyChanging();
					this._LastPostedImage = value;
					this.SendPropertyChanged("LastPostedImage");
					this.OnLastPostedImageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastFavedMe", DbType="DateTime2")]
		public System.Nullable<System.DateTime> LastFavedMe
		{
			get
			{
				return this._LastFavedMe;
			}
			set
			{
				if ((this._LastFavedMe != value))
				{
					this.OnLastFavedMeChanging(value);
					this.SendPropertyChanging();
					this._LastFavedMe = value;
					this.SendPropertyChanged("LastFavedMe");
					this.OnLastFavedMeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastCommentedMe", DbType="DateTime2")]
		public System.Nullable<System.DateTime> LastCommentedMe
		{
			get
			{
				return this._LastCommentedMe;
			}
			set
			{
				if ((this._LastCommentedMe != value))
				{
					this.OnLastCommentedMeChanging(value);
					this.SendPropertyChanging();
					this._LastCommentedMe = value;
					this.SendPropertyChanged("LastCommentedMe");
					this.OnLastCommentedMeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BuddyIconUrl", DbType="NVarChar(500)")]
		public string BuddyIconUrl
		{
			get
			{
				return this._BuddyIconUrl;
			}
			set
			{
				if ((this._BuddyIconUrl != value))
				{
					this.OnBuddyIconUrlChanging(value);
					this.SendPropertyChanging();
					this._BuddyIconUrl = value;
					this.SendPropertyChanged("BuddyIconUrl");
					this.OnBuddyIconUrlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IconFarm", DbType="NVarChar(300)")]
		public string IconFarm
		{
			get
			{
				return this._IconFarm;
			}
			set
			{
				if ((this._IconFarm != value))
				{
					this.OnIconFarmChanging(value);
					this.SendPropertyChanging();
					this._IconFarm = value;
					this.SendPropertyChanged("IconFarm");
					this.OnIconFarmChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IconServer", DbType="NVarChar(300)")]
		public string IconServer
		{
			get
			{
				return this._IconServer;
			}
			set
			{
				if ((this._IconServer != value))
				{
					this.OnIconServerChanging(value);
					this.SendPropertyChanging();
					this._IconServer = value;
					this.SendPropertyChanged("IconServer");
					this.OnIconServerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhotosUrl", DbType="NVarChar(500)")]
		public string PhotosUrl
		{
			get
			{
				return this._PhotosUrl;
			}
			set
			{
				if ((this._PhotosUrl != value))
				{
					this.OnPhotosUrlChanging(value);
					this.SendPropertyChanging();
					this._PhotosUrl = value;
					this.SendPropertyChanged("PhotosUrl");
					this.OnPhotosUrlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProfileUrl", DbType="NVarChar(500)")]
		public string ProfileUrl
		{
			get
			{
				return this._ProfileUrl;
			}
			set
			{
				if ((this._ProfileUrl != value))
				{
					this.OnProfileUrlChanging(value);
					this.SendPropertyChanging();
					this._ProfileUrl = value;
					this.SendPropertyChanged("ProfileUrl");
					this.OnProfileUrlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastReacted", DbType="DateTime2")]
		public System.Nullable<System.DateTime> LastReacted
		{
			get
			{
				return this._LastReacted;
			}
			set
			{
				if ((this._LastReacted != value))
				{
					this.OnLastReactedChanging(value);
					this.SendPropertyChanging();
					this._LastReacted = value;
					this.SendPropertyChanged("LastReacted");
					this.OnLastReactedChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
